# Generated by Django 4.2 on 2023-05-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_daily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='today_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='daily',
            name='yesterday_description',
            field=models.TextField(),
        ),
    ]
