# Generated by Django 2.2.4 on 2019-11-25 19:22

from django.db import migrations, models
import sorl.thumbnail.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='description',
            field=wagtail.core.fields.RichTextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='element',
            field=models.CharField(choices=[('Air', 'Air'), ('Arcane', 'Arcane'), ('Earth', 'Earth'), ('Fire', 'Fire'), ('Dark', 'Dark'), ('Light', 'Light'), ('Omni', 'Omni'), ('Water', 'Water')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='family',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Undead', 'Undead'), ('Beast', 'Beast'), ('Construct', 'Construct'), ('Dragon', 'Dragon')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monsterName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
