# Generated by Django 2.2.4 on 2019-11-25 19:34

from django.db import migrations, models
import sorl.thumbnail.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0002_auto_20191125_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='monster',
            name='element',
            field=models.CharField(blank=True, choices=[('Air', 'Air'), ('Arcane', 'Arcane'), ('Earth', 'Earth'), ('Fire', 'Fire'), ('Dark', 'Dark'), ('Light', 'Light'), ('Omni', 'Omni'), ('Water', 'Water')], default=('Air', 'Air'), max_length=30),
        ),
        migrations.AlterField(
            model_name='monster',
            name='family',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Undead', 'Undead'), ('Beast', 'Beast'), ('Construct', 'Construct'), ('Dragon', 'Dragon')], default=('Normal', 'Normal'), max_length=30),
        ),
        migrations.AlterField(
            model_name='monster',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monsterName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
