FROM oven/bun:1.0.1

# Cypress dependencies
RUN apt update && apt install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
RUN Xvfb :99 &

# Prepare main directory
WORKDIR /frontend
