FROM python:3.8.2

RUN apt-get update && apt-get install -yy gcc build-essential python-setuptools graphviz libgraphviz-dev

ENV PYTHONUNBUFFERED 1

ADD requirements.dev.txt .
ADD requirements.txt .
RUN pip install -r requirements.dev.txt

# Install inotify for gunicorn to nicely reload things..
RUN apt-get update && apt-get install -y inotify-tools

WORKDIR /app

ENV PYTHONPATH "${PYTHONPATH}:/app/src"
