FROM oven/bun:1.1.16

# Cypress dependencies
RUN apt update && apt install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb unzip

# Prepare main directory
WORKDIR /frontend
