# Generated by Django 2.2.4 on 2019-12-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('unity_id', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('element', models.CharField(max_length=20)),
            ],
        ),
    ]
