# Generated by Django 2.2.4 on 2019-12-06 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monster', '0002_monsta_image'),
        ('attacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damageDealt', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=5)),
                ('picked', models.BooleanField(default=False)),
                ('killed', models.BooleanField(default=False)),
                ('attacks', models.ManyToManyField(to='attacks.Attack')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binding', to='monster.Monsta')),
            ],
        ),
    ]
