# Generated by Django 2.2.4 on 2019-11-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monsta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monsterName', models.CharField(blank=True, max_length=50, null=True)),
                ('family', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Undead', 'Undead'), ('Beast', 'Beast'), ('Construct', 'Construct'), ('Dragon', 'Dragon')], default=('Normal', 'Normal'), max_length=30)),
                ('element', models.CharField(blank=True, choices=[('Air', 'Air'), ('Arcane', 'Arcane'), ('Earth', 'Earth'), ('Fire', 'Fire'), ('Dark', 'Dark'), ('Light', 'Light'), ('Omni', 'Omni'), ('Water', 'Water')], default=('Air', 'Air'), max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=510)),
            ],
        ),
    ]
