# Generated by Django 2.2.4 on 2019-12-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsta',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
