name: Skeletor testing

on:
  push:
    branches: [ '*' ]

env:
  COMPOSE_INTERACTIVE_NO_CLI: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all branches (for migration conflict checks)
          fetch-depth: 0

      - name: Clone Skeletor into "/tmp/new_project" directory
        env:
          SKELETOR_BRANCH: ${{ github.head_ref || github.ref_name }}
        run: |
          cd /tmp
          printf "%s\n" "new_project" "1" | $GITHUB_WORKSPACE/skeletor.sh

      - name: Test Skeletor in "/tmp/new_project" directory
        working-directory: /tmp/new_project
        run: |
          docker-compose exec -T django pytest
#
#      - name: Set up Python
#        uses: actions/setup-python@v3
#        with:
#          python-version: 3.10
#
#      - name: Install python dependencies
#        run: |
#          pip install -r requirements.dev.txt

#      - name: Test with pytest
#        run: |
#          cd src/backend && pytest

  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all branches (for migration conflict checks)
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.6

      - name: Lint with flake8
        run: |
          pip install $(cat requirements.dev.txt | grep flake8)
          cd src/backend && flake8
